version: '3.9'

services:
  redis1:
    image: redislabs/redisearch:latest
    ports:
      - 6379:6379
    volumes:
      - redis1-data:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
      - REDIS_MAXMEMORY=60mb  # Nueva variable de entorno

  redis2:
    image: redislabs/redisearch:latest
    ports:
      - 6380:6379
    volumes:
      - redis2-data:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
      - REDIS_MAXMEMORY=60mb  # Nueva variable de entorno

  redis3:
    image: redislabs/redisearch:latest
    ports:
      - 6381:6379
    volumes:
      - redis3-data:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
      - REDIS_MAXMEMORY=60mb  # Nueva variable de entorno

volumes:
  redis1-data:
  redis2-data:
  redis3-data:
